package com.google.android.gms.internal;

public enum zzae
{
  private final String zzhI;
  
  static
  {
    zzdA = new zzae("BLACKLISTED_BEHAVIOR", 19, "blacklisted_behavior");
    zzdB = new zzae("CACHE_BUSTER", 20, "cache_buster");
    zzdC = new zzae("CACHE_BUSTER_VALUE", 21, "cache_buster_value");
    zzdD = new zzae("CAMPAIGN_CONTENT_KEY", 22, "campaign_content_key");
    zzdE = new zzae("CAMPAIGN_CONTENT_OVERRIDE", 23, "campaign_content_override");
    zzdF = new zzae("CAMPAIGN_COOKIE_TIMEOUT", 24, "campaign_cookie_timeout");
    zzdG = new zzae("CAMPAIGN_MEDIUM_KEY", 25, "campaign_medium_key");
    zzdH = new zzae("CAMPAIGN_MEDIUM_OVERRIDE", 26, "campaign_medium_override");
    zzdI = new zzae("CAMPAIGN_NAME_KEY", 27, "campaign_name_key");
    zzdJ = new zzae("CAMPAIGN_NAME_OVERRIDE", 28, "campaign_name_override");
    zzdK = new zzae("CAMPAIGN_NO_KEY", 29, "campaign_no_key");
    zzdL = new zzae("CAMPAIGN_SOURCE_KEY", 30, "campaign_source_key");
    zzdM = new zzae("CAMPAIGN_SOURCE_OVERRIDE", 31, "campaign_source_override");
    zzdN = new zzae("CAMPAIGN_TERM_KEY", 32, "campaign_term_key");
    zzdO = new zzae("CAMPAIGN_TERM_OVERRIDE", 33, "campaign_term_override");
    zzdP = new zzae("CAMPAIGN_TRACK", 34, "campaign_track");
    zzdQ = new zzae("CATEGORY", 35, "category");
    zzdR = new zzae("CHECK_VALIDATION", 36, "check_validation");
    zzdS = new zzae("CHILD_INDEX", 37, "child_index");
    zzdT = new zzae("CLEAR_PERSISTENT_DATA_LAYER_PREFIX", 38, "clear_data_layer_prefix");
    zzdU = new zzae("CLICK_ID", 39, "click_id");
    zzdV = new zzae("CLIENT_INFO", 40, "client_info");
    zzdW = new zzae("COLLECT_ADID", 41, "collect_adid");
    zzdX = new zzae("COMPANY", 42, "company");
    zzdY = new zzae("COMPONENT", 43, "component");
    zzdZ = new zzae("CONTENT_DESCRIPTION", 44, "content_description");
    zzea = new zzae("CONTENT_GROUP", 45, "content_group");
    zzeb = new zzae("CONVERSION_ID", 46, "conversion_id");
    zzec = new zzae("COOKIE_DOMAIN", 47, "cookie_domain");
    zzed = new zzae("COOKIE_EXPIRATION", 48, "cookie_expiration");
    zzee = new zzae("COOKIE_NAME", 49, "cookie_name");
    zzef = new zzae("COOKIE_PATH", 50, "cookie_path");
    zzeg = new zzae("COOKIE_PATH_COPY", 51, "cookie_path_copy");
    zzeh = new zzae("COUNTRY", 52, "country");
    zzei = new zzae("CSS_ID", 53, "css_id");
    zzej = new zzae("CSS_IMPORTANT", 54, "css_important");
    zzek = new zzae("CSS_PROPERTY", 55, "css_property");
    zzel = new zzae("CSS_RULE", 56, "css_rule");
    zzem = new zzae("CSS_VALUE", 57, "css_value");
    zzen = new zzae("CURRENCY_CODE", 58, "currency_code");
    zzeo = new zzae("CUSTOM_URL_SOURCE", 59, "custom_url_source");
    zzep = new zzae("CUSTOM_VARS", 60, "custom_vars");
    zzeq = new zzae("CUSTOMER_ID", 61, "customer_id");
    zzer = new zzae("DATA_LAYER_VERSION", 62, "data_layer_version");
    zzes = new zzae("DATA_PROVIDER_ID", 63, "data_provider_id");
    zzet = new zzae("DEBUG", 64, "debug");
    zzeu = new zzae("DECODE", 65, "decode");
    zzev = new zzae("DECORATE_FORM", 66, "decorate_form");
    zzew = new zzae("DECORATE_FORMS_AUTO_LINK", 67, "decorate_forms_auto_link");
    zzex = new zzae("DECORATE_LINK", 68, "decorate_link");
    zzey = new zzae("DEFAULT_PAGES", 69, "default_pages");
    zzez = new zzae("DEFAULT_VALUE", 70, "default_value");
    zzeA = new zzae("DEPENDENCIES", 71, "dependencies");
    zzeB = new zzae("DETECT_FLASH", 72, "detect_flash");
    zzeC = new zzae("DETECT_TITLE", 73, "detect_title");
    zzeD = new zzae("DIMENSION", 74, "dimension");
    zzeE = new zzae("DOMAIN_NAME", 75, "domain_name");
    zzeF = new zzae("DOUBLE_CLICK", 76, "double_click");
    zzeG = new zzae("ECOMMERCE_MACRO_DATA", 77, "ecommerce_macro_data");
    zzeH = new zzae("ECOMMERCE_USE_DATA_LAYER", 78, "ecommerce_use_data_layer");
    zzeI = new zzae("ELEMENT", 79, "element");
    zzeJ = new zzae("ELEMENT_ID", 80, "element_id");
    zzeK = new zzae("ELEMENTS", 81, "elements");
    zzeL = new zzae("EMAIL", 82, "email");
    zzeM = new zzae("EMPLOYEE_RANGE", 83, "employee_range");
    zzeN = new zzae("ENABLE_ECOMMERCE", 84, "enable_ecommerce");
    zzeO = new zzae("ENABLE_ALL_VIDEOS", 85, "enable_all_videos");
    zzeP = new zzae("ENABLE_PRODUCT_REPORTING", 86, "enable_product_reporting");
    zzeQ = new zzae("ENABLE_REMARKETING_LISTS", 87, "enable_remarketing_lists");
    zzeR = new zzae("ESCAPE", 88, "escape");
    zzeS = new zzae("EVENT_ACTION", 89, "event_action");
    zzeT = new zzae("EVENT_CATEGORY", 90, "event_category");
    zzeU = new zzae("EVENT_LABEL", 91, "event_label");
    zzeV = new zzae("EVENT_VALUE", 92, "event_value");
    zzeW = new zzae("EXCEPTION_DESCRIPTION", 93, "exception_description");
    zzeX = new zzae("EXCEPTION_FATAL", 94, "exception_fatal");
    zzeY = new zzae("EXPERIMENT_COMBINATION", 95, "experiment_combination");
    zzeZ = new zzae("EXPERIMENT_ID", 96, "experiment_id");
    zzfa = new zzae("EXPERIMENT_KEY", 97, "experiment_key");
    zzfb = new zzae("FAILED_BEHAVIOR", 98, "failed_behavior");
    zzfc = new zzae("SECTION_INDEX", 99, "section_index");
    zzfd = new zzae("FIELDS_TO_SET", 100, "fields_to_set");
    zzfe = new zzae("FORCE_SSL", 101, "force_ssl");
    zzff = new zzae("FORM_OBJECT", 102, "form_object");
    zzfg = new zzae("FUNCTION", 103, "function");
    zzfh = new zzae("FUNCTION_CALL_NAME", 104, "function_call_macro_name");
    zzfi = new zzae("GROUP", 105, "group");
    zzfj = new zzae("HIT_CALLBACK", 106, "hit_callback");
    zzfk = new zzae("HTML", 107, "html");
    zzfl = new zzae("ID", 108, "id");
    zzfm = new zzae("IGNORED_ORGANIC", 109, "ignored_organic");
    zzfn = new zzae("IGNORED_REF", 110, "ignored_ref");
    zzfo = new zzae("IGNORE_CASE", 111, "ignore_case");
    zzfp = new zzae("INPUT", 112, "input");
    zzfq = new zzae("INPUT_FORMAT", 113, "input_format");
    zzfr = new zzae("INSTANCE_NAME", 114, "instance_name");
    zzfs = new zzae("INSTANCE_LABEL", 115, "instance_label");
    zzft = new zzae("INTERVAL", 116, "interval");
    zzfu = new zzae("ITEM_SEPARATOR", 117, "item_separator");
    zzfv = new zzae("JAVASCRIPT", 118, "javascript");
    zzfw = new zzae("JSON", 119, "json");
    zzfx = new zzae("KEYWORD", 120, "keyword");
    zzfy = new zzae("KEY_VALUE_SEPARATOR", 121, "key_value_separator");
    zzfz = new zzae("LABEL", 122, "label");
    zzfA = new zzae("LANGUAGE", 123, "language");
    zzfB = new zzae("LIMIT", 124, "limit");
    zzfC = new zzae("LINK", 125, "link");
    zzfD = new zzae("LINK_BY_POST", 126, "link_by_post");
    zzfE = new zzae("LINK_ID", 127, "link_id");
    zzfF = new zzae("LIVE_ONLY", 128, "live_only");
    zzfG = new zzae("LOCAL_GIF_PATH", 129, "local_gif_path");
    zzfH = new zzae("LOCALE", 130, "locale");
    zzfI = new zzae("LOCATION", 131, "location");
    zzfJ = new zzae("MAP", 132, "map");
    zzfK = new zzae("MAX", 133, "max");
    zzfL = new zzae("METRIC", 134, "metric");
    zzfM = new zzae("MIN", 135, "min");
    zzfN = new zzae("MODE", 136, "mode");
    zzfO = new zzae("NAME", 137, "name");
    zzfP = new zzae("NAMESPACE_CODE", 138, "namespace_code");
    zzfQ = new zzae("NAMESPACE_ID", 139, "namespace_id");
    zzfR = new zzae("NAMESPACE_VALUE", 140, "namespace_value");
    zzfS = new zzae("NONINTERACTION", 141, "noninteraction");
    zzfT = new zzae("NOT_DEFAULT_MACRO", 142, "not_default_macro");
    zzfU = new zzae("NO_PADDING", 143, "no_padding");
    zzfV = new zzae("NUMBER", 144, "number");
    zzfW = new zzae("OPTOUT", 145, "optout");
    zzfX = new zzae("ORDER", 146, "order");
    zzfY = new zzae("ORDER_ID", 147, "order_id");
    zzfZ = new zzae("ORDER_VALUE", 148, "order_value");
    zzga = new zzae("ORDINAL", 149, "ordinal");
    zzgb = new zzae("ORGANIC", 150, "organic");
    zzgc = new zzae("OUTPUT_FORMAT", 151, "output_format");
    zzgd = new zzae("PAGE", 152, "page");
    zzge = new zzae("PAGE_PATH", 153, "page_path");
    zzgf = new zzae("PARTITION", 154, "partition");
    zzgg = new zzae("PERCENTAGE", 155, "percentage");
    zzgh = new zzae("PIXEL", 156, "pixel");
    zzgi = new zzae("PLACEMENT", 157, "placement");
    zzgj = new zzae("PLATFORM", 158, "platform");
    zzgk = new zzae("POSITION", 159, "position");
    zzgl = new zzae("PRICES", 160, "prices");
    zzgm = new zzae("PRIORITY", 161, "priority");
    zzgn = new zzae("PRODUCT", 162, "product");
    zzgo = new zzae("PRODUCT_DATA", 163, "product_data");
    zzgp = new zzae("PRODUCT_ID", 164, "product_id");
    zzgq = new zzae("PRODUCT_IDS", 165, "product_ids");
    zzgr = new zzae("PRODUCT_SETTING_FIELD_PATH", 166, "product_setting_field_path");
    zzgs = new zzae("PUSH_AFTER_EVALUATE", 167, "push_after_evaluate");
    zzgt = new zzae("QUANTITY", 168, "quantity");
    zzgu = new zzae("QUERY_KEY", 169, "query_key");
    zzgv = new zzae("QUERY_LISTS", 170, "query_lists");
    zzgw = new zzae("REFERRER", 171, "referrer");
    zzgx = new zzae("REFERRER_OVERRIDE", 172, "referrer_override");
    zzgy = new zzae("REQUIRES_CONTENT", 173, "requires_content");
    zzgz = new zzae("REVENUE", 174, "revenue");
    zzgA = new zzae("SAMPLE_RATE", 175, "sample_rate");
    zzgB = new zzae("SELECTOR", 176, "selector");
    zzgC = new zzae("SEND_HITS_TO_GOOGLE", 177, "send_hits_to_google");
    zzgD = new zzae("SESSION_CONTROL", 178, "session_control");
    zzgE = new zzae("SESSION_COOKIE_TIMEOUT", 179, "session_cookie_timeout");
    zzgF = new zzae("SITE_SPEED_SAMPLE_RATE", 180, "site_speed_sample_rate");
    zzgG = new zzae("SOCIAL_ACTION", 181, "social_action");
    zzgH = new zzae("SOCIAL_ACTION_TARGET", 182, "social_action_target");
    zzgI = new zzae("SOCIAL_NETWORK", 183, "social_network");
    zzgJ = new zzae("SOCIAL_USE_DATA_LAYER", 184, "social_use_data_layer");
    zzgK = new zzae("SERVER_SIDE", 185, "server_side");
    zzgL = new zzae("STANDARD_INDUSTRIAL_CLASSIFICATION", 186, "standard_industrial_classification");
    zzgM = new zzae("STRING", 187, "string");
    zzgN = new zzae("STRIP_WWW", 188, "strip_www");
    zzgO = new zzae("TAG_ID", 189, "tag_id");
    zzgP = new zzae("TAG_LIST", 190, "tag_list");
    zzgQ = new zzae("TAG_LIST_CONTEXT", 191, "tag_list_context");
    zzgR = new zzae("TAG_LIST_INDEX", 192, "tag_list_index");
    zzgS = new zzae("TAG_REFERENCE", 193, "tag_reference");
    zzgT = new zzae("TARGET_CSS_ID", 194, "target_css_id");
    zzgU = new zzae("TARGET_ELEMENTS", 195, "target_elements");
    zzgV = new zzae("TARGET_SELECTOR", 196, "target_selector");
    zzgW = new zzae("TARGET_URL", 197, "target_url");
    zzgX = new zzae("TEXT", 198, "text");
    zzgY = new zzae("TIMING_CATEGORY", 199, "timing_category");
    zzgZ = new zzae("TIMING_LABEL", 200, "timing_label");
    zzha = new zzae("TIMING_SAMPLE_RATE", 201, "timing_sample_rate");
    zzhb = new zzae("TIMING_VALUE", 202, "timing_value");
    zzhc = new zzae("TIMING_VAR", 203, "timing_var");
    zzhd = new zzae("TITLE", 204, "title");
    zzhe = new zzae("TRACK_APPVIEW", 205, "track_appview");
    zzhf = new zzae("TRACK_DATA", 206, "track_data");
    zzhg = new zzae("TRACK_EVENT", 207, "track_event");
    zzhh = new zzae("TRACK_EXCEPTION", 208, "track_exception");
    zzhi = new zzae("TRACK_SOCIAL", 209, "track_social");
    zzhj = new zzae("TRACK_TIMING", 210, "track_timing");
    zzhk = new zzae("TRACK_TRANSACTION", 211, "track_transaction");
    zzhl = new zzae("TRACKER_NAME", 212, "tracker_name");
    zzhm = new zzae("TRACKING_ID", 213, "tracking_id");
    zzhn = new zzae("TRANSACTION_DATALAYER_MAP", 214, "transaction_datalayer_map");
    zzho = new zzae("TRANSACTION_ID", 215, "transaction_id");
    zzhp = new zzae("TRANSACTION_ITEM_DATALAYER_MAP", 216, "transaction_item_datalayer_map");
    zzhq = new zzae("TRANSACTION_VARIABLE", 217, "transaction_variable");
    zzhr = new zzae("TYPE", 218, "type");
    zzhs = new zzae("UNIQUE_TRIGGER_ID", 219, "unique_trigger_id");
    zzht = new zzae("UNREPEATABLE", 220, "unrepeatable");
    zzhu = new zzae("URL", 221, "url");
    zzhv = new zzae("USE_DATA_LAYER", 222, "use_data_layer");
    zzhw = new zzae("USE_HASH", 223, "use_hash");
    zzhx = new zzae("USE_IFRAME", 224, "use_iframe");
    zzhy = new zzae("USE_IMAGE_TAG", 225, "use_image_tag");
    zzhz = new zzae("USE_POSTSCRIBE", 226, "use_postscribe");
  }
  
  private zzae(String paramString)
  {
    this.zzhI = paramString;
  }
  
  public String toString()
  {
    return this.zzhI;
  }
}


/* Location:              /Users/michael/Downloads/dex2jar-2.0/HappyFresh.jar!/com/google/android/gms/internal/zzae.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */